
export default function ShapeAnimation({large}) {
    return (
        <>


            <div className={`${!large ? "block sm:hidden" : 'large'} shape-animation-wrpr`}>
                <div className="center">
                    <div className="grid">
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                        <div className="row_">
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                            <div className="particle" />
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
